[package]
name = "factory-time"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
heron = { version = "2.3.0", features = ["3d", "debug-3d"] }
bevy-inspector-egui = "0.9.0"